server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/fitness_microservice
    username: root
    password: qwertyuiop

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  eureka:
    client:
      serviceUrl:
        defaultZone:http://localhost:8761/eureka/


